consum <- read.table("household_power_consumption.txt",skip=1,sep=";")
names(consum) <- c("Date","Time","Global_active_power","Global_reactive_power","Voltage","Global_intensity","Sub_metering_1","Sub_metering_2","Sub_metering_3")
subconsum <- subset(consum,consum$Date=="1/2/2007" | consum$Date =="2/2/2007")
subconsum$Date <- as.Date(subconsum$Date, format="%d/%m/%Y")
subconsum$Time <- strptime(subconsum$Time, format="%H:%M:%S")
subconsum[1:1440,"Time"] <- format(subconsum[1:1440,"Time"],"2007-02-01 %H:%M:%S")
subconsum[1441:2880,"Time"] <- format(subconsum[1441:2880,"Time"],"2007-02-02 %H:%M:%S")
plot(subconsum$Time,as.numeric(as.character(subconsum$Global_active_power)),type="l",xlab="",ylab="Global Active Power (kilowatts)") 
title(main="Global Active Power Vs Time")
